version: "3.9"

services:
  webapp:
    restart: always
    build:
      context: ./
    ports:
      - "8000:8000"
    entrypoint: /app/entrypoint.sh
    command: >
      sh -c  "python3 manage.py runserver 0.0.0.0:8000"

    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:10-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - "5432:5432"

volumes:
  postgres_data:
